package ru.itmo.wp.model.repository.impl;

import ru.itmo.wp.model.domain.User;
import ru.itmo.wp.model.exception.RepositoryException;
import ru.itmo.wp.model.repository.UserRepository;
import ru.itmo.wp.model.repository.wrapper.UserWrapper;
import ru.itmo.wp.model.repository.wrapper.Wrapper;

import java.sql.*;
import java.util.List;

public class UserRepositoryImpl extends AbstractRepositoryImpl<User> implements UserRepository {
    private static final Wrapper<User> USER_WRAPPER = new UserWrapper();
    private static final String TABLE_NAME = "User";

    @Override
    protected String getTableName() {
        return TABLE_NAME;
    }

    @Override
    protected Wrapper<User> getElementWrapper() {
        return USER_WRAPPER;
    }

    @Override
    public User find(long id) {
        return findById(id);
    }

    @Override
    public User findByLogin(String login) {
        return findByAllArguments(new String[]{"login"}, new Object[]{login});
    }

    @Override
    public User findByLoginAndPasswordSha(String token, String passwordSha) {
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM " + TABLE_NAME + " WHERE login=? AND passwordSha=?")) {
                statement.setString(1, token);
                statement.setString(2, passwordSha);
                try (ResultSet resultSet = statement.executeQuery()) {
                    return USER_WRAPPER.wrap(statement.getMetaData(), resultSet);
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't find User.", e);
        }
    }

    public void save(User user, String passwordSha) {
        try (Connection connection = DATA_SOURCE.getConnection()) {
            String sqlRequest = getSaveSqlRequest(List.of("login", "admin", "passwordSha"));
            try (PreparedStatement statement = connection.prepareStatement(sqlRequest, Statement.RETURN_GENERATED_KEYS)) {
                statement.setString(1, user.getLogin());
                statement.setBoolean(2, user.isAdmin());
                statement.setString(3, passwordSha);
                if (statement.executeUpdate() != 1) {
                    throw new RepositoryException("Can't save User.");
                } else {
                    ResultSet generatedKeys = statement.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        user.setId(generatedKeys.getLong(1));
                        user.setCreationTime(this.findById(user.getId()).getCreationTime());
                    } else {
                        throw new RepositoryException("Can't save User [no autogenerated fields].");
                    }
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't save User.", e);
        }
    }

    @Override
    public User save(User element) {
        throw new RepositoryException("Saving user without password is unsupported operation");
    }
}
