package ru.itmo.wp.model.repository.impl;

import ru.itmo.wp.model.database.DatabaseUtils;
import ru.itmo.wp.model.exception.RepositoryException;
import ru.itmo.wp.model.repository.wrapper.WrapAble;
import ru.itmo.wp.model.repository.wrapper.Wrapper;

import javax.sql.DataSource;
import java.sql.*;
import java.util.*;
import java.util.stream.Collectors;

public abstract class AbstractRepositoryImpl<T extends WrapAble> {
    protected final DataSource DATA_SOURCE = DatabaseUtils.getDataSource();

    protected abstract String getDataBaseName();

    protected abstract Wrapper<T> getElementWrapper();

    public T findById(long id) {
        return findByAllArguments(new String[]{"id"}, new Object[]{id});
    }

    public List<T> findAll() {
        List<T> elements = new ArrayList<>();
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM " + getDataBaseName())) {
                try (ResultSet resultSet = statement.executeQuery()) {
                    T element;
                    while ((element = getElementWrapper().wrap(statement.getMetaData(), resultSet)) != null) {
                        elements.add(element);
                    }
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't find element in Data Base " + getDataBaseName(), e);
        }
        return elements;
    }

    public int findCount() {
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement preparedStatement = connection.prepareStatement("SELECT COUNT(*) FROM " + getDataBaseName())) {
                try (ResultSet resultSet = preparedStatement.executeQuery()) {
                    resultSet.next();
                    return resultSet.getInt(1);
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't count elements in Data Base " + getDataBaseName(), e);
        }
    }

    protected T findByAllArguments(String[] argumentNames, Object[] argumentValues) {
        String query = Arrays.stream(argumentNames)
                .map(e -> e + "=?")
                .collect(Collectors.joining(" AND "));

        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM " + getDataBaseName() + " WHERE " + query)) {
                for (int i = 0; i < argumentNames.length; i++) {
                    statement.setObject(i + 1, argumentValues[i]);
                }
                try (ResultSet resultSet = statement.executeQuery()) {
                    return getElementWrapper().wrap(statement.getMetaData(), resultSet);
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't find element in Data Base " + getDataBaseName(), e);
        }
    }

    public T save(T element) {
        try (Connection connection = DATA_SOURCE.getConnection()) {
            Map<String, Object> unwrapFields = element.unwrap();
            try (PreparedStatement statement = connection.prepareStatement(getSaveSqlRequest(unwrapFields.keySet()), Statement.RETURN_GENERATED_KEYS)) {
                int index = 1;
                for (Object value : unwrapFields.values()) {
                    statement.setObject(index++, value);
                }
                if (statement.executeUpdate() != 1) {
                    throw new RepositoryException("Can't save element.");
                } else {
                    ResultSet generatedKeys = statement.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        long id = generatedKeys.getLong(1);
                        element.setId(id);
                        element.setCreationTime(this.findById(id).getCreationTime());
                        return element;
                    } else {
                        throw new RepositoryException("Can't save element [no autogenerated fields].");
                    }
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't save element.", e);
        }
    }

    protected String getSaveSqlRequest(Collection<String> unwrapFields) {
        String fields = unwrapFields.stream().map(e -> '`' + e + '`').collect(Collectors.joining(", "));
        String valuesSql = String.join(", ", Collections.nCopies(unwrapFields.size(), "?"));


        String s = "INSERT INTO `" + getDataBaseName() + "` (" + fields + ", `creationTime`) VALUES (" + valuesSql + ", NOW())";
        System.out.println(s);
        return s;
    }
}
