package ru.itmo.wp.model.repository.impl;

import ru.itmo.wp.model.domain.Event;
import ru.itmo.wp.model.exception.RepositoryException;
import ru.itmo.wp.model.repository.EventRepository;
import ru.itmo.wp.model.repository.Wrapper;
import ru.itmo.wp.model.repository.wrapper.EventWrapper;

import java.sql.*;
import java.util.List;

public class EventRepositoryImpl extends AbstractRepositoryImpl<Event> implements EventRepository {
    private final Wrapper<Event> eventWrapper = new EventWrapper();
    private final String DATA_BASE_NAME = "Event";

    @Override
    protected String getDataBaseName() {
        return DATA_BASE_NAME;
    }

    @Override
    protected Wrapper<Event> getElementWrapper() {
        return eventWrapper;
    }

    @Override
    public Event find(long id) {
        return findById(id);
    }

    @Override
    public List<Event> findAll() {
        return findAllOrderedById();
    }

    @Override
    public void save(Event event) {
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("INSERT INTO `" + DATA_BASE_NAME + "` (`userId`, `type`, `creationTime`) VALUES (?, ?, NOW())", Statement.RETURN_GENERATED_KEYS)) {
                statement.setLong(1, event.getUserId());
                statement.setObject(2, event.getType());
                if (statement.executeUpdate() != 1) {
                    throw new RepositoryException("Can't save Event.");
                } else {
                    ResultSet generatedKeys = statement.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        event.setId(generatedKeys.getLong(1));
                        event.setCreationTime(find(event.getId()).getCreationTime());
                    } else {
                        throw new RepositoryException("Can't save Event [no autogenerated fields].");
                    }
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't save Event.", e);
        }
    }
}
