package ru.itmo.wp.model.repository.impl;

import ru.itmo.wp.model.domain.User;
import ru.itmo.wp.model.exception.RepositoryException;
import ru.itmo.wp.model.repository.UserRepository;
import ru.itmo.wp.model.repository.Wrapper;
import ru.itmo.wp.model.repository.wrapper.UserWrapper;

import java.sql.*;
import java.util.List;
import java.util.stream.Collectors;


public class UserRepositoryImpl extends AbstractRepositoryImpl implements UserRepository {
    private final Wrapper<User> userWrapper = new UserWrapper();
    private final String DATA_BASE_NAME = "User";

    @Override
    protected String getDataBaseName() {
        return DATA_BASE_NAME;
    }

    @Override
    protected Wrapper<?> getElementWrapper() {
        return userWrapper;
    }

    @Override
    public User find(long id) {
        return (User) findById(id);
    }

    @Override
    public User findByLogin(String login) {
        return (User) findByArguments(new String[]{"login"}, new Object[]{login});
    }

    @Override
    public User findByEmail(String email) {
        return (User) findByArguments(new String[]{"email"}, new Object[]{email});
    }

    @Override
    public List<User> findAll() {
        List<Object> users = findAllOrderedById();
        return users.stream()
                .map(element -> (User) element)
                .collect(Collectors.toList());
    }

    @Override
    public User findByLoginOrEmailAndPasswordSha(String token, String passwordSha) {
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM User WHERE (login=? OR email=?) AND passwordSha=?")) {
                statement.setString(1, token);
                statement.setString(2, token);
                statement.setString(3, passwordSha);
                try (ResultSet resultSet = statement.executeQuery()) {
                    return userWrapper.wrap(statement.getMetaData(), resultSet);
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't find User.", e);
        }
    }

    public void save(User user, String passwordSha) {
        try (Connection connection = DATA_SOURCE.getConnection()) {
            try (PreparedStatement statement = connection.prepareStatement("INSERT INTO `User` (`login`, `email`, `passwordSha`, `creationTime`) VALUES (?, ?, ?, NOW())", Statement.RETURN_GENERATED_KEYS)) {
                statement.setString(1, user.getLogin());
                statement.setString(2, user.getEmail());
                statement.setString(3, passwordSha);
                if (statement.executeUpdate() != 1) {
                    throw new RepositoryException("Can't save User.");
                } else {
                    ResultSet generatedKeys = statement.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        user.setId(generatedKeys.getLong(1));
                        user.setCreationTime(find(user.getId()).getCreationTime());
                    } else {
                        throw new RepositoryException("Can't save User [no autogenerated fields].");
                    }
                }
            }
        } catch (SQLException e) {
            throw new RepositoryException("Can't save User.", e);
        }
    }
}
